_posts/2016-06-13-the-shell-project.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide/9)
=> shell project overview

_posts/2016-07-09-shell-driver-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide/16)
=> title update

_posts/2016-04-05-cloudshell-developer-guide.md, _posts/2016-04-30-getting-started.markdown, _posts/2016-05-15-python-coding-standards.md, _posts/2016-06-13-the-shell-project.md, _posts/2016-06-14-setting-up-the-development-ide.md, _posts/2016-06-27-customizing-driver-commands.md, _posts/2016-07-09-shell-driver-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide/17)
=> adding order

_plugins/jekyll-prism-plugin.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide/18)
=> adding modeling section

_shells/discovering-inventory-snmp.md
closes #42 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/50)
=> updating windows snmp info

_devops/devops-integration.md
without the quotes it will fail.
also made another text change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/49)
=> added quotes for the pip install

_includes/header.html, _layouts/page.html, search.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/54)
=> fixing search layout

index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/55)
=> updated title

_layouts/page.html
Added the feature to go straight to the corresponding markdown file on Github, making it easier to anyone to contribute, change typos, etc.
Since Github provides easy ways of creating forks and PRs, this solution provides for a totally friction-less experience.
See how it works here: http://sht.tl/vJQAZd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/57)
=> added link to suggest edits

_shells/modeling-the-shell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/66)
=> fixing typo

_orchestration/8.1.0/common-orchestration-recipes.md, _orchestration/8.1.0/getting-information-from-cloudshell.md, _orchestration/8.1.0/script-commands-customization.md, _orchestration/8.1.0/scripts-deep-dive.md, _orchestration/8.1.0/the-oob-orchestration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/69)
=> fix some minor typos and links

_orchestration/8.1.0/the-oob-orchestration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/72)
=> update number of stages

_shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/76)
=> Shells getting started

_shells/8.0.0/getting-started.md
s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/78)
=> minor edit

_orchestration/8.1.0/the-oob-orchestration.md
documented the 4 setup stages + descriptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/75)
=> updated "Extending the OOB Setup Orchestration Scripts"

_plugins/jekyll_lunr_js_search.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/86)
=> search inside article content

_devops/7.1.0/devops-integration.md, _devops/8.0.0/devops-integration.md, _devops/8.1.0/devops-integration.md, _plugins/jekyll_lunr_js_search.rb, _shells/7.1.0/getting-started.md, _shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/84)
=> updated 7.1.0 and 8.1.0 shells Getting Started articles

_shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md
added step 1: setting CS server and user creds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/79)
=> basic flow - updates (8.0.0 and 8.1.0)

_config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/92)
=> change default version

_devops/7.1.0/devops-integration.md, _devops/8.0.0/devops-integration.md, _devops/8.1.0/devops-integration.md, _devops/8.2.0/devops-integration.md
- updated -python -m pip install "cloudshell-automation-api> versions
- removed limitations from section "Sandbox REST API Missing and Upcoming Features"
- fixed overview in sectoin "Executing Orchestration Commands"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/89)
=> 163824, item 2 (8.0, 8.1, 8.2)

_shells/8.0.0/modeling-the-shell.md, _shells/8.1.0/modeling-the-shell.md, _shells/8.2.0/modeling-the-shell.md
updated versions 8.0, 8.1, 8.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/90)
=> 164099 - fixed attribute tag names

_shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md
added to dev guide versions 8.0, 8.1, 8.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/91)
=> New Customizing a 2nd Gen Shell article

_config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/95)
=> update default documentation to be 8.2 for the EA release

_introduction/7.1.0/the-cloudshell-devguide.md, _introduction/8.0.0/the-cloudshell-devguide.md, _introduction/8.1.0/the-cloudshell-devguide.md, _introduction/8.2.0/the-cloudshell-devguide.md, _orchestration/7.1.0/getting-started.md, _orchestration/8.0.0/getting-started.md, _orchestration/8.1.0/getting-started.md, _orchestration/8.2.0/getting-started.md, _shells/7.1.0/getting-started.md, _shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md, _shells/8.2.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/96)
=> overview ref to Quali U in getting started articles

_reference/8.0.0/shellfoundry-intro.md, _reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/97)
=> added release note for 1.0.4 to Shellfoundry article 8.0/8.1/8.2

_orchestration/8.2.0/script-commands-customization.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/104)
=> fix issue #102

_reference/8.0.0/quali-shell-framework.md, _reference/8.1.0/quali-shell-framework.md, _reference/8.2.0/quali-shell-framework.md, _shells/8.0.0/common-driver-recipes.md, _shells/8.0.0/customizing-shells.md, _shells/8.0.0/deploying-to-production.md, _shells/8.1.0/common-driver-recipes.md, _shells/8.1.0/customizing-shells.md, _shells/8.1.0/deploying-to-production.md, _shells/8.2.0/common-driver-recipes.md, _shells/8.2.0/customizing-shells.md, _shells/8.2.0/deploying-to-production.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/105)
=> Quali Shell Framework - typo

_config.yml, _includes/disqus.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/108)
=> use site.home instead of site.url in disqus.html

_orchestration/8.1.0/the-oob-orchestration.md, _reference/8.0.0/quali-shell-framework.md, _reference/8.1.0/quali-shell-framework.md, _reference/8.2.0/quali-shell-framework.md, _shells/8.0.0/common-driver-recipes.md, _shells/8.0.0/customizing-shells.md, _shells/8.0.0/deploying-to-production.md, _shells/8.1.0/common-driver-recipes.md, _shells/8.1.0/customizing-shells.md, _shells/8.1.0/deploying-to-production.md, _shells/8.2.0/common-driver-recipes.md, _shells/8.2.0/customizing-shells.md, _shells/8.2.0/deploying-to-production.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/107)
=> Customizing Shells>attributes sections - minor phrasing updates

_shells/8.0.0/customizing-shells.md, _shells/8.0.0/deploying-to-production.md, _shells/8.1.0/customizing-shells.md, _shells/8.1.0/deploying-to-production.md, _shells/8.2.0/customizing-shells.md, _shells/8.2.0/deploying-to-production.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/109)
=> Dev guide changes 2

_layouts/default.html, opensearch.xml, search/search.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/112)
=> add opensearchdescription tryout

_reference/8.0.0/shellfoundry-intro.md, _reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/114)
=> Shellfoundry - updated version history to release 1.1.5

_shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md, _shells/8.3.0/customizing-shells.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/117)
=> Customizing Shells - note + ref for adding discovery attributes

_shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md, _shells/8.3.0/customizing-shells.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/119)
=> 166646: Customizing shells - end-to-end example - minor edits

_shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md, _shells/8.3.0/customizing-shells.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/121)
=> customizing shells - shell extension example - minor phrasing change

_reference/8.0.0/shellfoundry-intro.md, _reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md, _shells/8.3.0/customizing-shells.md
change shell template to shell in sections discussing extending a shell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/123)
=> Customizing Shells/Shellfoundry articles - extend

_reference/8.0.0/shellfoundry-intro.md, _reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _shells/8.0.0/customizing-shells.md, _shells/8.1.0/customizing-shells.md, _shells/8.2.0/customizing-shells.md, _shells/8.3.0/customizing-shells.md
shell template > shell, minor typo - "commnunity", updated path value description for extend command
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/124)
=> Customizing shells/Shellfoundry - additional extend updates

_shells/8.0.0/modeling-the-shell.md, _shells/8.1.0/modeling-the-shell.md, _shells/8.2.0/modeling-the-shell.md, _shells/8.3.0/modeling-the-shell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/134)
=> Modeling the Shell - fixed "template_icon" description

CNAME
Reverts QualiSystems/devguide_source#136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/137)
=> Revert "add CNAME"

_config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/139)
=> remove site.baseurl

opensearch.xml, search/7.1.0/search.md, search/8.0.0/search.md, search/8.1.0/search.md, search/8.2.0/search.md, search/8.3.0/search.md, search/search.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/140)
=> fix search not working

_shells/8.0.0/modeling-the-shell.md, _shells/8.1.0/modeling-the-shell.md, _shells/8.2.0/modeling-the-shell.md, _shells/8.3.0/modeling-the-shell.md
fixed formatting on to do statement "To see the attributes in CloudShell:"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/141)
=> Modeling shells - formatting

_shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md, _shells/8.2.0/getting-started.md, _shells/8.3.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/152)
=> Shells Getting Started article - minor typo

_reference/8.0.0/L1-switch-shell.md, _reference/8.1.0/L1-switch-shell.md, _reference/8.2.0/L1-switch-shell.md, _reference/8.3.0/L1-switch-shell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/153)
=> L1 switch shell article - formatting

_reference/8.0.0/short-dev-videos.md, _reference/8.1.0/short-dev-videos.md, _reference/8.2.0/short-dev-videos.md, _reference/8.3.0/short-dev-videos.md, _shells/7.1.0/driver-deep-dive.md, _shells/8.0.0/customizing-shells.md, _shells/8.0.0/driver-deep-dive.md, _shells/8.0.0/getting-started.md, _shells/8.0.0/modeling-the-shell.md, _shells/8.1.0/customizing-shells.md, _shells/8.1.0/driver-deep-dive.md, _shells/8.1.0/getting-started.md, _shells/8.1.0/modeling-the-shell.md, _shells/8.2.0/customizing-shells.md, _shells/8.2.0/driver-deep-dive.md, _shells/8.2.0/getting-started.md, _shells/8.2.0/modeling-the-shell.md, _shells/8.3.0/customizing-shells.md, _shells/8.3.0/driver-deep-dive.md, _shells/8.3.0/getting-started.md, _shells/8.3.0/modeling-the-shell.md
Embedded videos throughout the dev guide
Added article "Short Development Videos"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/155)
=> 167831 - added shell dev videos to dev guide versions 8.0-8.3

_reference/8.0.0/short-dev-videos.md, _reference/8.1.0/short-dev-videos.md, _reference/8.2.0/short-dev-videos.md, _reference/8.3.0/short-dev-videos.md, _shells/8.0.0/customizing-shells.md, _shells/8.0.0/driver-deep-dive.md, _shells/8.1.0/customizing-shells.md, _shells/8.1.0/driver-deep-dive.md, _shells/8.2.0/customizing-shells.md, _shells/8.2.0/driver-deep-dive.md, _shells/8.3.0/customizing-shells.md, _shells/8.3.0/driver-deep-dive.md
updated the video to mention min and max cloudshell0-automation-api package versions -- requested by Roni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/157)
=> 167831 - Updated API Commands video

_cloudproviders/9.0.0/L2-networking-management.md, _cloudproviders/9.0.0/L3-networking-management.md, _cloudproviders/9.0.0/app-deployment.md, _cloudproviders/9.0.0/extending-cloud-provider-shell-data-model.md, _cloudproviders/9.0.0/resource-discovery.md, _introduction/7.1.0/the-cloudshell-devguide.md, _introduction/8.0.0/the-cloudshell-devguide.md, _introduction/8.1.0/the-cloudshell-devguide.md, _introduction/8.2.0/the-cloudshell-devguide.md, _introduction/8.3.0/the-cloudshell-devguide.md, _introduction/9.0.0/the-cloudshell-devguide.md, _reference/8.0.0/short-dev-videos.md, _reference/8.1.0/short-dev-videos.md, _reference/8.2.0/short-dev-videos.md, _reference/8.3.0/short-dev-videos.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/168)
=> Dev guide 9.0 ea

_reference/8.0.0/shellfoundry-intro.md, _reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _shells/8.0.0/getting-started.md, _shells/8.1.0/getting-started.md, _shells/8.2.0/getting-started.md, _shells/8.3.0/getting-started.md, _shells/9.0.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/172)
=> New suggestion for /reference/8.3.0/shellfoundry-intro.html #165

_cloudproviders/9.0.0/app-deployment.md, _reference/7.1.0/python-coding-standards.md, _reference/8.0.0/python-coding-standards.md, _reference/8.1.0/python-coding-standards.md, _reference/8.2.0/python-coding-standards.md, _reference/8.3.0/python-coding-standards.md, _reference/9.0.0/python-coding-standards.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/174)
=> cloud providers - typo

_cloudproviders/9.0.0/app-deployment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/176)
=> App Deployment - update

_cloudproviders/9.0.0/L2-networking-management.md, _cloudproviders/9.0.0/L3-networking-management.md, _cloudproviders/9.0.0/app-deployment.md, _cloudproviders/9.0.0/power-off-and-delete.md, _cloudproviders/9.0.0/resource-discovery.md, tests/cibuild
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/180)
=> cloud providers - ResourceRemoteCommandContext code examples

_cloudproviders/9.0.0/app-deployment.md, _cloudproviders/9.0.0/power-off-and-delete.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/181)
=> (CLP) missing code example for uuid in power on/off/delete

_reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/194)
=> 9.1 ga - shellfoundry version 1.2.6 updates

_reference/8.1.0/shellfoundry-intro.md, _reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/195)
=> shellfoundry - delete - supported in 9.1 GA note

_shells/8.2.0/customizing-shells.md, _shells/8.2.0/modeling-the-shell.md, _shells/8.3.0/customizing-shells.md, _shells/8.3.0/modeling-the-shell.md, _shells/9.0.0/customizing-shells.md, _shells/9.0.0/modeling-the-shell.md, _shells/9.1.0/customizing-shells.md, _shells/9.1.0/modeling-the-shell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/196)
=> 8.2-9.1 - 170274 - support for spaces in attribute names

_reference/8.2.0/shellfoundry-intro.md, _reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/198)
=> shellfoundry get_templates downloads latest patch-compatible templates

_reference/8.2.0/creating-static-vm.md, _reference/8.3.0/creating-static-vm.md, _reference/9.0.0/creating-static-vm.md, _reference/9.1.0/creating-static-vm.md, _reference/9.2.0/creating-static-vm.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/204)
=> static vms article - add attributes before generate

_orchestration/8.3.0/getting-started.md, _orchestration/8.3.0/scripts-deep-dive.md, _orchestration/9.0.0/getting-started.md, _orchestration/9.0.0/scripts-deep-dive.md, _orchestration/9.1.0/getting-started.md, _orchestration/9.1.0/scripts-deep-dive.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.2.0/scripts-deep-dive.md
Orchestration Getting Started - new section
Scripts Deep Dive - reference to new section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/206)
=> 171154 - recommended cloudshell lib requirements per version

_reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/208)
=> 171259 - 'shellfoundry dist' command

_reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/209)
=> shellfoundry - dist command - phrasing update

_reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/210)
=> shellfoundry 1.2.10 version history

_reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md, _shells/8.3.0/customizing-shells.md, _shells/9.0.0/customizing-shells.md, _shells/9.1.0/customizing-shells.md, _shells/9.2.0/customizing-shells.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/211)
=> shellfoundry extend - fixed source code description

_reference/8.3.0/shellfoundry-intro.md, _reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/212)
=> shrlldoundry - typo

_config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/214)
=> 9.2 config.yml - 9.2 default

_orchestration/9.0.0/the-oob-orchestration.md, _orchestration/9.1.0/the-oob-orchestration.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.2.0/the-oob-orchestration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/218)
=> 171738 - setup cannot be executed via Restore scripts using APIs

_cloudproviders/9.0.0/app-deployment.md, _cloudproviders/9.1.0/app-deployment.md, _cloudproviders/9.2.0/app-deployment.md
app-deployment.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/220)
=> remote_refresh_ip return value documentation

_introduction/9.0.0/the-cloudshell-devguide.md, _introduction/9.1.0/the-cloudshell-devguide.md, _introduction/9.2.0/the-cloudshell-devguide.md, _introduction/9.3.0/the-cloudshell-devguide.md, _orchestration/8.3.0/getting-started.md, _orchestration/9.0.0/getting-started.md, _orchestration/9.1.0/getting-started.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.3.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/221)
=> Version 9.3

_reference/9.0.0/shellfoundry-intro.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.2.0/shellfoundry-intro.md, _reference/9.3.0/shellfoundry-intro.md, _shells/9.0.0/getting-started.md, _shells/9.1.0/getting-started.md, _shells/9.2.0/getting-started.md, _shells/9.3.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/238)
=> 173505: --python attribute

_reference/9.3.0/common-cloudshell-packages.md, _reference/9.3.0/migrating-shells-to-python-3.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/246)
=> common cloudshell packages and python 3 migration articles

_reference/9.3.0/quali-shell-framework-python-3.md, _shells/9.3.0/tips-and-tricks.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/247)
=> 173510 - Devguide - python 3 shell packages

_devops/9.0.0/available-apis.md, _devops/9.1.0/available-apis.md, _devops/9.2.0/available-apis.md, _devops/9.3.0/available-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/248)
=> 173533 - python script that starts a session outside of cloudshell

_reference/9.2.0/working-with-sandbox-metadata.md, _reference/9.3.0/working-with-sandbox-metadata.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/249)
=> 173710 - Custom Sandbox Metadata: end-to-end example

_reference/9.2.0/working-with-sandbox-metadata.md, _reference/9.3.0/working-with-sandbox-metadata.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/250)
=> custom sandbox metadata - minor formatting

_shells/9.0.0/customizing-driver-commands.md, _shells/9.1.0/customizing-driver-commands.md, _shells/9.2.0/customizing-driver-commands.md, _shells/9.3.0/customizing-driver-commands.md
improved overview, added some notes and an implementation example at the bottom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/257)
=> connected commands section - updates

_shells/9.0.0/common-driver-recipes.md, _shells/9.0.0/customizing-driver-commands.md, _shells/9.1.0/common-driver-recipes.md, _shells/9.1.0/customizing-driver-commands.md, _shells/9.2.0/common-driver-recipes.md, _shells/9.2.0/customizing-driver-commands.md, _shells/9.3.0/common-driver-recipes.md, _shells/9.3.0/customizing-driver-commands.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/260)
=> Connected commands moved to Common Driver Recipes

_cloudproviders/9.3.0/getting-started-with-cloud-providers.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.3.0/getting-started.md, _shells/9.3.0/getting-started.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/262)
=> 174904 - vc++ 2015 required for shell/script venvs

_reference/2020.1.0/resource-scripts.md, _reference/9.1.0/resource-scripts.md, _reference/9.2.0/resource-scripts.md, _reference/9.3.0/resource-scripts.md
need for __main__.py
how to import into cloudShell and link to shell models
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/264)
=> resource scripts - added missing explanation

_orchestration/2020.1.0/getting-information-from-cloudshell.md, _orchestration/9.0.0/getting-information-from-cloudshell.md, _orchestration/9.1.0/getting-information-from-cloudshell.md, _orchestration/9.2.0/getting-information-from-cloudshell.md, _orchestration/9.3.0/getting-information-from-cloudshell.md
since 9.0, not 9.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/265)
=> running_user for orch scripts

_shells/2020.1.0/customizing-driver-commands.md, _shells/9.1.0/customizing-driver-commands.md, _shells/9.2.0/customizing-driver-commands.md, _shells/9.3.0/customizing-driver-commands.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/266)
=> 174867 - "admin only" shell driver commands

_reference/2020.1.0/resource-scripts.md, _reference/2020.1.0/short-dev-videos.md, _reference/9.1.0/resource-scripts.md, _reference/9.1.0/short-dev-videos.md, _reference/9.2.0/resource-scripts.md, _reference/9.2.0/short-dev-videos.md, _reference/9.3.0/resource-scripts.md, _reference/9.3.0/short-dev-videos.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/267)
=> creating resource scripts video

_cloudproviders/2020.1.0/creating-cloud-provider-shell.md, _cloudproviders/9.1.0/creating-cloud-provider-shell.md, _cloudproviders/9.2.0/creating-cloud-provider-shell.md, _cloudproviders/9.3.0/creating-cloud-provider-shell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/269)
=> customer cloud provider link

_cloudproviders/2020.1.0/getting-started-with-cloud-providers.md, _cloudproviders/9.3.0/getting-started-with-cloud-providers.md, _orchestration/2020.1.0/getting-started.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.3.0/getting-started.md, _shells/2020.1.0/getting-started.md, _shells/9.3.0/getting-started.md
in Microsoft Visual C++ Redistributable 2015 Redistributable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/270)
=> typo - redundant "Redistributable"

_orchestration/2020.1.0/getting-information-from-cloudshell.md, _orchestration/2020.1.0/getting-started.md, _orchestration/2020.1.0/the-oob-orchestration.md, _orchestration/9.1.0/getting-information-from-cloudshell.md, _orchestration/9.1.0/getting-started.md, _orchestration/9.1.0/the-oob-orchestration.md, _orchestration/9.2.0/getting-information-from-cloudshell.md, _orchestration/9.2.0/getting-started.md, _orchestration/9.2.0/the-oob-orchestration.md, _orchestration/9.3.0/getting-information-from-cloudshell.md, _orchestration/9.3.0/getting-started.md, _orchestration/9.3.0/the-oob-orchestration.md, _reference/2020.1.0/shellfoundry-intro.md, _reference/2020.1.0/short-dev-videos.md, _reference/9.1.0/shellfoundry-intro.md, _reference/9.1.0/short-dev-videos.md, _reference/9.2.0/shellfoundry-intro.md, _reference/9.2.0/short-dev-videos.md, _reference/9.3.0/shellfoundry-intro.md, _reference/9.3.0/short-dev-videos.md, _shells/2020.1.0/discovering-inventory-snmp.md, _shells/7.1.0/discovering-inventory-snmp.md, _shells/8.0.0/discovering-inventory-snmp.md, _shells/8.1.0/discovering-inventory-snmp.md, _shells/8.2.0/discovering-inventory-snmp.md, _shells/8.3.0/discovering-inventory-snmp.md, _shells/9.0.0/discovering-inventory-snmp.md, _shells/9.1.0/discovering-inventory-snmp.md, _shells/9.2.0/discovering-inventory-snmp.md, _shells/9.3.0/discovering-inventory-snmp.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/271)
=> customizing ootb orchestration scripts video

_orchestration/2020.1.0/the-oob-orchestration.md, _orchestration/9.2.0/the-oob-orchestration.md, _orchestration/9.3.0/the-oob-orchestration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/276)
=> 42433 - enable_stageName=False doesn't apply to preparation stage

_reference/2020.1.0/shellfoundry-intro.md
Downloading offline shell template - additional steps - https://github.com/QualiSystems/devguide_source/issues/278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/devguide_source/279)
=> Release 2020 1
